# Generated by Django 4.2.5 on 2023-09-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_desc', models.CharField(max_length=50)),
                ('cat_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
