# Generated by Django 4.2.5 on 2023-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.FileField(upload_to='images'),
        ),
    ]
