# Generated by Django 4.2.5 on 2023-10-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0005_brand_brd_status_category_cat_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_img', models.FileField(upload_to='images')),
                ('p2_img', models.FileField(upload_to='images')),
                ('prd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hps.product')),
            ],
        ),
    ]
