# Generated by Django 4.2.5 on 2023-10-07 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0006_prdimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrdVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.FileField(upload_to='images')),
                ('stock', models.IntegerField()),
                ('cur_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('p1_img', models.FileField(upload_to='images')),
                ('p2_img', models.FileField(upload_to='images')),
                ('p3_img', models.FileField(upload_to='images')),
                ('prd_status', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cur_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prd_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='PrdImage',
        ),
        migrations.AddField(
            model_name='prdvariation',
            name='prd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hps.product'),
        ),
    ]
