# Generated by Django 4.2.5 on 2023-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0007_prdvariation_remove_product_cur_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdvariation',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
