# Generated by Django 4.2.5 on 2023-10-08 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0010_alter_cart_prd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prd_var',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hps.prdvariation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='prd_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hps.product'),
        ),
    ]
