# Generated by Django 4.2.5 on 2023-10-11 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0013_order_payment_orderitem_order_new_order_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='val',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='del_add',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='hps.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 13, 44, 17, 716630)),
        ),
    ]
