# Generated by Django 4.2.5 on 2023-10-11 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0014_cart_val_order_del_add_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razor_pay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 19, 14, 16, 315199)),
        ),
    ]
