# Generated by Django 4.2.5 on 2023-10-14 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0016_order_pay_method_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 20, 6, 27, 150050)),
        ),
    ]
