# Generated by Django 4.2.5 on 2023-10-19 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0018_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 20, 40, 4, 677433)),
        ),
    ]
