# Generated by Django 4.2.5 on 2023-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0021_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ban_img',
            new_name='ban1_img',
        ),
        migrations.AddField(
            model_name='banner',
            name='ban2_img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='ban3_img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='banner',
            name='ban4_img',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
