# Generated by Django 4.2.5 on 2023-10-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0023_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='description',
        ),
    ]
