# Generated by Django 4.2.5 on 2023-10-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0026_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='remove_address',
            field=models.BooleanField(default=True),
        ),
    ]
