# Generated by Django 4.2.5 on 2023-10-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hps', '0027_address_remove_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=10),
        ),
    ]
